
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-project-abc-shop-tls
  namespace: argocd
spec:
  secretName: argo-project-abc-shop-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.project-abc.shop
  dnsNames:
  - argo.project-abc.shop